# configuration
# fill in the course details
 
courseName: Digital Humanities for the Ancient World

# small title that is at the top of every page
subtitle: DHAW2022 | CLCV 25922/1 - CLAS 35922/1 | Autumn 2022

# baseurl is the same as the name of the repository
baseurl: /DHAW2022

# url where the required reading is available to download
docsUrl: "" 

# url where the student's grading info is kept
gradingUrl: "" 


# change only if you know what you are doing
collections:
  syllabus:
    output: true
defaults:
  - scope:
      path: ""
      type: syllabus
    values:
      layout: unit
